# Generated by Django 6.1 on 2026-08-26 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionCita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_cita', models.DateField()),
                ('estado', models.CharField(choices=[('ATENDIDO', 'Atendido'), ('FALTO', 'Faltó'), ('NO_PAGO', 'No pagó (no se atendió)')], default='ATENDIDO', max_length=10)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la cita')),
                ('evolucion', models.TextField(blank=True, verbose_name='Evolución del tratamiento')),
                ('firma', models.TextField(blank=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atencion', to='citas.cita')),
                ('medico_atendio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='citas.medico')),
            ],
            options={
                'verbose_name': 'Atención de cita',
                'verbose_name_plural': 'Atenciones de cita',
                'ordering': ['-fecha_cita'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDO', 'Válido'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validacion', to='citas.pago')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validación de pago',
                'verbose_name_plural': 'Validaciones de pago',
            },
        ),
    ]
