# Generated by Django 6.1 on 2026-08-26 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_atencioncita_validacionpago'),
        ('pacientes', '0003_documentohistoriaclinica_odontograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='citas.serviciodental'),
        ),
    ]
