# Generated by Django 6.1 on 2026-08-27 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_pago_cliente_pago_comprobante_pago_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciodental',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio dental', 'verbose_name_plural': 'Servicios dentales'},
        ),
        migrations.AddField(
            model_name='serviciodental',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subservicios', to='citas.serviciodental'),
        ),
    ]
