# Generated by Django 6.1 on 2026-08-30 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_serviciodental_options_serviciodental_padre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacionpago',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='validacionpago',
            name='validado_por',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='ValidacionPago',
        ),
    ]
