# Generated by Django 6.1 on 2026-09-14 05:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_notaagenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_sillones', models.PositiveIntegerField(default=1, verbose_name='Capacidad de sillones')),
                ('ubicacion_interna', models.CharField(blank=True, help_text='Ej: "Piso 2, Ala Izquierda", "Al fondo junto a recepción"', max_length=150, verbose_name='Ubicación interna')),
                ('equipamiento_especial', models.TextField(blank=True, help_text='Ej: "Máquina de Rayos X integrada, cámara intraoral"')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
                'ordering': ['nombre'],
            },
        ),
    ]
