# Generated by Django 6.1 on 2026-09-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_cita_consultorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciodental',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de producto'),
        ),
        migrations.AddField(
            model_name='serviciodental',
            name='moneda',
            field=models.CharField(choices=[('PEN', 'S/ (Soles)'), ('USD', 'US$ (Dólares)')], default='PEN', max_length=3),
        ),
    ]
