# Generated by Django 6.1 on 2026-09-14 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_serviciodental_codigo_serviciodental_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Producto')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock mínimo')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='serviciodental',
            name='insumos',
            field=models.ManyToManyField(blank=True, related_name='servicios', to='citas.insumo'),
        ),
    ]
