# Generated by Django 6.1 on 2026-08-26 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinicaDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alergias', models.TextField(blank=True)),
                ('pulmonares', models.TextField(blank=True)),
                ('cardiacas', models.TextField(blank=True)),
                ('neurologicas', models.TextField(blank=True)),
                ('hepaticas', models.TextField(blank=True)),
                ('renales', models.TextField(blank=True)),
                ('endocrino', models.TextField(blank=True)),
                ('musculo_esqueletico', models.TextField(blank=True)),
                ('otras_enfermedades', models.TextField(blank=True)),
                ('enfermedad_cronica_tratamiento', models.TextField(blank=True)),
                ('cartilla_vacunacion_completa', models.TextField(blank=True)),
                ('problema_comportamiento', models.TextField(blank=True)),
                ('lactancia_materna', models.TextField(blank=True)),
                ('experiencia_dental_previa', models.TextField(blank=True)),
                ('revision_sistemica', models.TextField(blank=True)),
                ('labios', models.TextField(blank=True)),
                ('carrillos', models.TextField(blank=True)),
                ('paladar_duro', models.TextField(blank=True)),
                ('paladar_blando', models.TextField(blank=True)),
                ('encias', models.TextField(blank=True)),
                ('lengua', models.TextField(blank=True)),
                ('piso_de_boca', models.TextField(blank=True)),
                ('orofaringe', models.TextField(blank=True)),
                ('atm', models.TextField(blank=True, verbose_name='ATM (articulación temporomandibular)')),
                ('higiene', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Detalle de historia clínica',
                'verbose_name_plural': 'Detalles de historia clínica',
            },
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias', to='pacientes.historiaclinicadetalle'),
        ),
    ]
