# Generated by Django 6.1 on 2026-08-26 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_historiaclinicadetalle_historiaclinica_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoHistoriaClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('DNI', 'DNI / Documento de identidad'), ('RADIOGRAFIA', 'Radiografía'), ('CONSENTIMIENTO', 'Consentimiento informado'), ('RECETA', 'Receta'), ('RESULTADO', 'Resultado de laboratorio'), ('FOTOGRAFIA', 'Fotografía clínica'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('archivo', models.FileField(upload_to='historias/documentos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.historiaclinica')),
            ],
            options={
                'verbose_name': 'Documento de historia clínica',
                'verbose_name_plural': 'Documentos de historia clínica',
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('dientes', models.JSONField(blank=True, default=dict)),
                ('especificaciones', models.TextField(blank=True)),
                ('informe_radiografico', models.TextField(blank=True)),
                ('higiene_bucal', models.TextField(blank=True)),
                ('ihos', models.TextField(blank=True, verbose_name='IHOS')),
                ('diagnostico', models.TextField(blank=True)),
                ('cie', models.CharField(blank=True, max_length=20, verbose_name='CIE')),
                ('plan_tratamiento', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas', to='pacientes.historiaclinica')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
            },
        ),
    ]
