# Generated by Django 6.1 on 2026-08-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_documentohistoriaclinica_odontograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('TIKTOK', 'TikTok'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('GOOGLE', 'Google / búsqueda web'), ('RECOMENDADO', 'Recomendado por un paciente'), ('FERIA', 'Feria / campaña'), ('PASO', 'Pasó por el local'), ('OTRO', 'Otro')], max_length=15, verbose_name='¿De dónde viene el paciente?'),
        ),
    ]
