# Generated by Django 6.1 on 2026-08-27 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_procedencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesPersonales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alergias', models.TextField(blank=True, help_text='Alergia a algún medicamento, alimento o sustancia (especificar)', null=True)),
                ('enfermedades_pulmonares', models.TextField(blank=True, help_text='TBC, asma, influenza, etc.', null=True)),
                ('enfermedades_cardiacas', models.TextField(blank=True, help_text='Hipertensión, valvulopatías, soplo, etc.', null=True)),
                ('enfermedades_neurologicas', models.TextField(blank=True, help_text='Epilepsia, Parkinson, ausencias, trastornos mentales, emocionales o nerviosos', null=True)),
                ('enfermedades_hepaticas', models.TextField(blank=True, help_text='Ictericia, hepatitis, cirrosis, etc.', null=True)),
                ('enfermedades_renales', models.TextField(blank=True, help_text='Insuficiencia, cálculos, infecciones, etc.', null=True)),
                ('sistema_endocrino', models.TextField(blank=True, help_text='Diabetes, hipotiroidismo, etc.', null=True)),
                ('musculo_esqueletico', models.TextField(blank=True, help_text='Reuma, artritis, artrosis, etc.', null=True)),
                ('otras_enfermedades', models.TextField(blank=True, help_text='Otras enfermedades no especificadas arriba', null=True)),
                ('enfermedad_cronica_y_tratamiento', models.TextField(blank=True, help_text='Enfermedad crónica que padece y tratamiento que recibe', null=True)),
                ('cartilla_vacunacion_completa', models.BooleanField(default=False, help_text='¿Cuenta con cartilla de vacunación completa?')),
                ('problema_comportamiento', models.TextField(blank=True, help_text='Problemas de comportamiento (especificar)', null=True)),
                ('lactancia_materna', models.CharField(blank=True, help_text='Tiempo y tipo de lactancia materna', max_length=255, null=True)),
                ('experiencia_dental_previa', models.TextField(blank=True, help_text='Experiencia dental previa (especificar)', null=True)),
                ('revision_sistemica', models.TextField(blank=True, help_text='Revisión sistémica (indicar lo restante)', null=True)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.historiaclinica')),
            ],
            options={
                'verbose_name': 'Antecedentes personales',
                'verbose_name_plural': 'Antecedentes personales',
            },
        ),
    ]
