# Generated by Django 6.1 on 2026-09-01 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_antecedentespersonales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='detalle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia', to='pacientes.historiaclinicadetalle'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='historia_clinica', to='pacientes.paciente'),
        ),
    ]
