# Generated by Django 6.1 on 2026-09-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alter_historiaclinica_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de WhatsApp'),
        ),
    ]
