# Generated by Django 6.1 on 2026-09-14 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_insumo_serviciodental_insumos'),
        ('pacientes', '0007_paciente_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evolucion', models.TextField(verbose_name='Evolución')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evoluciones', to='citas.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Evolución',
                'verbose_name_plural': 'Evoluciones',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
