# Generated by Django 6.1 on 2026-09-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_insumo_serviciodental_insumos'),
        ('pacientes', '0008_evolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucion',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones', to='citas.cita'),
        ),
    ]
