# Generated by Django 6.1 on 2026-08-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'SOPORTE'), ('MANAGER', 'ADMINISTRADOR'), ('ASSISTANT', 'ASISTENTE'), ('MEDICO', 'MÉDICO')], default='ASSISTANT', max_length=150),
        ),
    ]
