# Generated by Django 6.1 on 2026-08-31 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_remove_validacionpago_pago_and_more'),
        ('ventas', '0002_pago_fecha_validacion_pago_observacion_validacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='citas.cita'),
        ),
    ]
