# Generated by Django 6.1 on 2026-09-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_notaagenda'),
        ('ventas', '0003_venta_cita'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(fields=('venta', 'numero'), name='cuota_numero_unico_por_venta'),
        ),
    ]
